server:
  port: 10001
spring:
  application:
    name: user-consumer
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  zipkin:
    base-url: http://127.0.0.1:8080/
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    producer:
      bootstrap-servers: 39.105.108.217:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://polunzi:123@123.206.14.25:7776/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}