server:
  port: 10001
spring:
  application:
    name: user-consumer
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
eureka:
  client:
    service-url:
      defaultZone: http://polunzi:123@123.206.14.25:7776/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}