server:
  port: 10000
spring:
  application:
    name: user-provide
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/jshm?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Ws123456.
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 180000
      connection-timeout: 5000
    tomcat:
      test-on-borrow: true

eureka:
  client:
    service-url:
      defaultZone: http://polunzi:123@123.206.14.25:7776/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true

